FROM alpine:3.10

WORKDIR /var/submariner

# These are all available in the UBI8 base OS repository
RUN apk add --update iptables ip6tables ipset iproute2 && \
   rm -rf /var/cache/apk/*

COPY submariner-route-agent.sh /usr/local/bin

RUN chmod +x /usr/local/bin/submariner-route-agent.sh

COPY submariner-route-agent /usr/local/bin


# temporary sleep infinity so that we can do our debugging
ENTRYPOINT /usr/local/bin/submariner-route-agent.sh
